# Generated by Django 4.2.1 on 2023-05-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraftmodel",
            name="part_id",
            field=models.ForeignKey(
                db_column="part_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="part_id",
                to="aircraft.part",
            ),
        ),
    ]
