# Generated by Django 4.2.1 on 2023-05-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0006_partdetails_part_part_detail_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="model_id",
            field=models.ForeignKey(
                db_column="model_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aircraft_model",
                to="aircraft.aircraftmodel",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="part_detail_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="part_details",
                to="aircraft.partdetails",
            ),
        ),
    ]
