# Generated by Django 4.2.1 on 2023-05-13 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("material_composition", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("condition", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("potential_use_case", models.CharField(default=None, max_length=100)),
                ("recycle_rate", models.FloatField(default=0)),
                ("remanufacturing_potential", models.FloatField(default=0)),
                ("renew_material_content", models.FloatField(default=0)),
                ("toxic_score_difference", models.FloatField(default=0)),
                ("remanufacturing_potential_percent", models.FloatField(default=0)),
                ("lifecycle_assesment", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="AircraftModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("manufacturer_name", models.CharField(max_length=100)),
                (
                    "part_id",
                    models.ForeignKey(
                        db_column="part_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_id",
                        to="aircraft.part",
                    ),
                ),
            ],
        ),
    ]
