# Generated by Django 4.2.1 on 2023-05-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0003_rename_id_part_part_id_alter_aircraftmodel_part_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraftmodel",
            name="part_id",
        ),
        migrations.AddField(
            model_name="part",
            name="model_id",
            field=models.OneToOneField(
                db_column="model_id",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aircraft_model_id",
                to="aircraft.aircraftmodel",
            ),
            preserve_default=False,
        ),
    ]
