# Generated by Django 4.2.1 on 2023-05-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0004_remove_aircraftmodel_part_id_part_model_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="model_id",
            field=models.ForeignKey(
                db_column="model_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aircraft_model_id",
                to="aircraft.aircraftmodel",
            ),
        ),
    ]
