# Generated by Django 4.2.1 on 2023-05-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0005_alter_part_model_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("new_part_water_usage", models.IntegerField(default=0)),
                ("new_part_energy_consumption", models.IntegerField(default=0)),
                ("new_part_landfill_waste", models.IntegerField(default=0)),
                ("new_part_part_carbon_footprint", models.IntegerField(default=0)),
                ("new_part_toxicity_score", models.FloatField(default=0)),
                ("renew_part_energy_consumption", models.FloatField(default=0)),
                ("renew_part_water_usage", models.IntegerField(default=0)),
                ("renew_part_landfill_waste", models.IntegerField(default=0)),
                ("renew_part_carbon_foot_print", models.IntegerField(default=0)),
                ("renew_part_toxicity_score", models.FloatField(default=0)),
                ("carbon_footprint_saved", models.FloatField(default=0)),
                ("water_usage_saved", models.FloatField(default=0)),
                ("landfill_waste_saved", models.FloatField(default=0)),
                ("energy_saved", models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="part",
            name="part_detail_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="part_details_id",
                to="aircraft.partdetails",
            ),
            preserve_default=False,
        ),
    ]
