# Generated by Django 4.2.1 on 2023-05-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0007_alter_part_model_id_alter_part_part_detail_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="partdetails",
            name="life_cycle_assesment_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="part",
            name="part_detail_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="part_details",
                to="aircraft.partdetails",
            ),
        ),
    ]
